import os
import sys
import shutil
import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

# Add src to path
sys.path.append(os.path.join(os.getcwd(), "src"))

from visual_guard.visual import VisualTester
from visual_guard.report import SimpleReporter

def run_browser_test():
    # Setup directories
    baseline_dir = "tests_browser/baselines"
    snapshot_dir = "tests_browser/snapshots"
    diff_dir = os.path.join(snapshot_dir, "diffs")
    
    if os.path.exists(snapshot_dir): shutil.rmtree(snapshot_dir)
    os.makedirs(baseline_dir, exist_ok=True)
    os.makedirs(snapshot_dir, exist_ok=True)
    os.makedirs(diff_dir, exist_ok=True)

    # Initialize VisualTester and Reporter
    tester = VisualTester(baseline_dir=baseline_dir, snapshot_dir=snapshot_dir)
    reporter = SimpleReporter(title="Visual Guard Browser Test Report")

    # Setup Selenium (Headless for speed/CI, but Chrome is fine)
    options = Options()
    if os.environ.get("CI"):
        options.add_argument("--headless")
        options.add_argument("--no-sandbox")
        options.add_argument("--disable-dev-shm-usage")
    # options.add_argument("--headless")  # Commented out for visualization
    options.add_argument("--window-size=1280,1024")
    # You might need to specify driver path or assume it's in path
    # Assuming chrome is installed.
    
    print("Starting browser...")
    driver = webdriver.Chrome(options=options)
    
    try:
        # Test Case 1: Simple Page Match
        print("Test 1: Example Domain")
        driver.get("https://example.com")
        time.sleep(3) # Wait for render and user observation
        
        test_name = "example_home"
        passed = tester.assert_matches(driver, test_name) # Pass driver directly!
        
        status = "PASSED" if passed else "FAILED"
        reporter.add_result(
            name=test_name,
            status=status,
            baseline_path=os.path.join(baseline_dir, test_name + ".png"),
            snapshot_path=os.path.join(snapshot_dir, test_name + ".png"),
            diff_path=os.path.join(diff_dir, test_name + "_diff.png") if not passed else None
        )
        print(f"Test 1 {status}")

        # Test Case 2: Induced Failure (Modify DOM)
        print("Test 2: Modified DOM")
        # Inject JS to change content
        driver.execute_script("document.querySelector('h1').innerText = 'Changed Title';")
        driver.execute_script("document.querySelector('p').style.backgroundColor = 'yellow';")
        time.sleep(3) # Wait for user to see the change
        
        test_name = "example_modified"
        # We reuse the same name 'example_home' via a new test name for baseline comparison?
        # Typically visual regression compares same test name over time.
        # To simulate failure in a demo, we need a baseline that differs from current.
        # Let's create a baseline from the original state first (already done in Test 1).
        # We'll compare this Modified state against 'example_home' baseline.
        
        # Manually invoke comparison against 'example_home' baseline but save as 'example_modified_check'
        # VisualTester.assert_matches computes paths based on name.
        # So to compare against 'example_home', we really want to say "Check if this matches example_home".
        # But if we pass 'example_home', it will overwrite the snapshot we just took?
        # VisualTester implementation saves snapshot to f"{name}.png".
        # If we use same name, it overwrites.
        # So we can effectively re-run "example_home" check with modified state.
        
        passed = tester.assert_matches(driver, "example_home")
        
        # This time we expect failure (unless first run created baseline just now).
        # Report logic:
        # If we just ran Test 1, baseline exists.
        # Now we run again with modified page. It should fail.
        
        status = "PASSED" if passed else "FAILED"
        # Note: diff path is generated by tester
        reporter.add_result(
            name="example_home_mutation", # Distinct name for report
            status=status,
            baseline_path=os.path.join(baseline_dir, "example_home.png"),
            snapshot_path=os.path.join(snapshot_dir, "example_home.png"), # It overwrote this
            diff_path=os.path.join(diff_dir, "example_home_diff.png")
        )
        print(f"Test 2 {status} (Expected FAILED)")

    except Exception as e:
        print(f"Error: {e}")
    finally:
        driver.quit()
        
    # Generate Report
    report_file = "visual_report.html"
    reporter.generate(report_file)
    print(f"Report generated: {report_file}")

if __name__ == "__main__":
    run_browser_test()
